import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By "Rudra"
      </p>
      <ul>
        <li>
          <Link to="/cashapp">CashApp</Link>
        </li>
        <li>
          <Link to="/cashapp1">CashApp1</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
